modLoader="javafml"
loaderVersion="[36,)"

license="LGPLv3"
issueTrackerURL="https://github.com/Hellish-Mods/Hellish-Powah/issues"

[[mods]]
modId="powah"
version="${file.jarVersion}"

displayName="Powah: Overcharged"
displayURL="https://www.curseforge.com/minecraft/mc-mods/powah"
logoFile="pack.png"

authors="Hellish Mods & Modern Modpacks"
credits="""
owmii (Original author)
Rainbuu (Coding, Assets)
G_cat (Tech support, Coding, Assets)
"""
description="A fork of the mod Powah to add more customizability for Modern Modpacks."

[[dependencies.powah]]
    modId="forge"
    mandatory=true

    versionRange="[36.0.0,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.powah]]
    modId="minecraft"
    mandatory=true

    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.powah]]
    modId="lollipop"
    mandatory=true

    versionRange="[3.2.9,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.powah]]
    modId="jei"
    mandatory=false

    versionRange=","
    ordering="NONE"
    side="CLIENT"
[[dependencies.powah]]
    modId="patchouli"
    mandatory=false

    versionRange="[1.16.4-53.2,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.powah]]
    modId="kubejs"
    mandatory=false

    versionRange=","
    ordering="NONE"
    side="BOTH"

